# Generated by Django 2.2.5 on 2019-09-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.City')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessinalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.City')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zips', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=6)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessinalUser')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ServiceType')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessinalUser')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.GeneralUser')),
            ],
        ),
        migrations.AddField(
            model_name='professinaluser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.State'),
        ),
        migrations.AddField(
            model_name='professinaluser',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Vendor'),
        ),
        migrations.AddField(
            model_name='professinaluser',
            name='zips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Zip'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.State'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='zips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Zip'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.State'),
        ),
    ]
