# Generated by Django 2.2.5 on 2019-10-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RateMyServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Service'),
        ),
        migrations.AddField(
            model_name='rating',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessionalUser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ImageField(upload_to='static/images/ads')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessionalUser')),
            ],
        ),
    ]
