# Generated by Django 2.2.5 on 2019-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0002_auto_20190911_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
