# Generated by Django 2.2.5 on 2019-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0005_auto_20191120_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_pics/'),
        ),
    ]
