# Generated by Django 2.2.5 on 2019-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0005_auto_20190923_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
