# Generated by Django 2.2.5 on 2019-12-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0006_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaluser',
            name='isDiamond',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionaluser',
            name='isPlatinum',
            field=models.BooleanField(default=False),
        ),
    ]
