# Generated by Django 2.2.5 on 2019-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0006_auto_20190923_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaluser',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
