# Generated by Django 2.2.5 on 2019-12-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0007_auto_20191204_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hireCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
