# Generated by Django 2.2.5 on 2019-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0007_professionaluser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaluser',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
