# Generated by Django 2.2.5 on 2019-10-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0009_professionaluser_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.GeneralUser')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessionalUser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Service')),
            ],
        ),
    ]
