# Generated by Django 2.2.5 on 2019-10-12 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0009_professionaluser_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaluser',
            name='generalUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
