# Generated by Django 2.2.5 on 2019-10-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0010_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.Service'),
        ),
        migrations.AddField(
            model_name='rating',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
