# Generated by Django 2.2.5 on 2019-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0011_auto_20191011_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.FloatField(),
        ),
    ]
