# Generated by Django 2.2.5 on 2019-10-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyServices', '0012_auto_20191011_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.GeneralUser')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ImageField(upload_to='static/images/ads')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyServices.ProfessionalUser')),
            ],
        ),
    ]
