# Generated by Django 2.2.5 on 2019-10-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191011_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.BooleanField(default=False),
        ),
    ]
